// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class gosterimSaat_gosterimGun : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gosterimSaat_gosterimGun));
        
        string IMigrationMetadata.Id
        {
            get { return "202210101027457_gosterimSaat_gosterimGun"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
