// <auto-generated />
namespace DataAccesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class films_added_seoUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(films_added_seoUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "202210071016313_films_added_seoUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
